/**
 * build.mjs — src/ → dist/
 *
 * Produces exactly four kinds of file, and the split is the performance
 * contract the site depends on:
 *
 *   dist/rc.critical.css   synchronous, kept small
 *   dist/rc.css            asynchronous, everything else
 *   dist/rc.js             the runtime, a deferred module
 *   dist/components/*.js   one chunk per component, fetched on demand
 *
 * dist/ is committed: jsDelivr serves it straight from the repository.
 *
 * Sources that do not exist yet are skipped, so the build runs clean while
 * src/ is still being written and reports what it found.
 */

import {
  access,
  readFile,
  writeFile,
  mkdir,
  rm,
  readdir,
} from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";
import * as esbuild from "esbuild";

const root = fileURLToPath(new URL("..", import.meta.url));
const src = path.join(root, "src");
const dist = path.join(root, "dist");

const GENERATED_HEADER = `/*! Generated by scripts/build.mjs — do not edit. Source: src/ */\n`;

async function exists(file) {
  try {
    await access(file);
    return true;
  } catch {
    return false;
  }
}

async function existing(files) {
  const kept = [];
  for (const file of files) if (await exists(file)) kept.push(file);
  return kept;
}

/** Component folders, each expected to hold `<name>.js` and `<name>.css`. */
async function findComponents() {
  const entries = await readdir(path.join(src, "components"), {
    withFileTypes: true,
  });
  return entries
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .sort();
}

async function buildScripts(components) {
  const candidates = { rc: path.join(src, "runtime", "index.js") };
  for (const name of components) {
    candidates[`components/${name}`] = path.join(
      src,
      "components",
      name,
      `${name}.js`,
    );
  }

  const entryPoints = {};
  for (const [name, file] of Object.entries(candidates)) {
    if (await exists(file)) entryPoints[name] = file;
  }
  if (Object.keys(entryPoints).length === 0) return 0;

  await esbuild.build({
    entryPoints,
    outdir: dist,
    bundle: true,
    // Shared runtime and a11y code lands in one chunk instead of being copied
    // into every component.
    splitting: true,
    chunkNames: "chunks/[name]-[hash]",
    format: "esm",
    target: "es2022",
    minify: true,
    sourcemap: true,
  });

  return Object.keys(entryPoints).length;
}

/** Returns the minified byte count, or null when no source exists yet. */
async function bundleStyles(sources, outFile) {
  const files = await existing(sources);
  if (files.length === 0) return null;

  const parts = [];
  for (const file of files) {
    parts.push(await readFile(file, "utf8"));
  }
  // `/*!` headers in the sources survive minification, so each block stays
  // attributable in the shipped file.
  const { code } = await esbuild.transform(parts.join("\n"), {
    loader: "css",
    minify: true,
  });
  await writeFile(outFile, GENERATED_HEADER + code);
  return code.length;
}

/** Clear only what this script owns; anything else in dist/ survives. */
async function clearOwnOutput() {
  const owned = [
    "chunks",
    "components",
    "rc.js",
    "rc.js.map",
    "rc.css",
    "rc.critical.css",
  ];
  for (const entry of owned) {
    await rm(path.join(dist, entry), { recursive: true, force: true });
  }
  await mkdir(dist, { recursive: true });
}

function report(label, bytes) {
  return `${label.padEnd(16)}${bytes === null ? "no source yet" : `${bytes} B`}`;
}

async function main() {
  const components = await findComponents();

  await clearOwnOutput();

  const scriptCount = await buildScripts(components);

  const criticalBytes = await bundleStyles(
    [path.join(src, "base", "critical.css")],
    path.join(dist, "rc.critical.css"),
  );

  const mainBytes = await bundleStyles(
    [
      path.join(src, "base", "motion.css"),
      path.join(src, "base", "site.css"),
      ...components.map((name) =>
        path.join(src, "components", name, `${name}.css`),
      ),
    ],
    path.join(dist, "rc.css"),
  );

  console.log(
    [
      `components      ${components.length} (${components.join(", ") || "none"})`,
      `js entries      ${scriptCount}`,
      report("rc.critical.css", criticalBytes),
      report("rc.css", mainBytes),
    ].join("\n"),
  );
}

await main();
