/**
 * build.mjs — src/ → dist/ and webflow/embeds/head.html
 *
 * Three outputs, and the split is the performance contract the site depends on:
 *
 *   webflow/embeds/head.html   critical CSS inlined, version stamped — pasted
 *                              into Webflow; nothing in it leaves the page
 *   dist/rc.css                asynchronous, everything else
 *   dist/rc.js + components/   the runtime (deferred) and one chunk per
 *                              component, fetched on demand
 *
 * dist/ and head.html are committed: the CDN (see cdn-ref.mjs) serves dist/
 * straight from the repository, and head.html is what the Webflow head must
 * match exactly.
 *
 * Sources that do not exist yet are skipped, so the build runs clean while
 * src/ is still being written and reports what it found.
 */

import {
  access,
  readFile,
  writeFile,
  mkdir,
  rm,
  readdir,
} from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";
import * as esbuild from "esbuild";
import { cdnLocation } from "./cdn-ref.mjs";

const root = fileURLToPath(new URL("..", import.meta.url));
const src = path.join(root, "src");
const dist = path.join(root, "dist");
const embeds = path.join(root, "webflow", "embeds");

const GENERATED_HEADER = `/*! Generated by scripts/build.mjs — do not edit. Source: src/ */\n`;

/** Where runtime/motion.js and runtime/scroll.js fetch GSAP and Lenis. */
const LIBRARY_ORIGIN = "https://cdn.jsdelivr.net";

async function exists(file) {
  try {
    await access(file);
    return true;
  } catch {
    return false;
  }
}

async function existing(files) {
  const kept = [];
  for (const file of files) if (await exists(file)) kept.push(file);
  return kept;
}

/** Component folders, each expected to hold `<name>.js` and `<name>.css`. */
async function findComponents() {
  const entries = await readdir(path.join(src, "components"), {
    withFileTypes: true,
  });
  return entries
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .sort();
}

async function buildScripts(components) {
  const candidates = { rc: path.join(src, "runtime", "index.js") };
  for (const name of components) {
    candidates[`components/${name}`] = path.join(
      src,
      "components",
      name,
      `${name}.js`,
    );
  }

  const entryPoints = {};
  for (const [name, file] of Object.entries(candidates)) {
    if (await exists(file)) entryPoints[name] = file;
  }
  if (Object.keys(entryPoints).length === 0) return 0;

  await esbuild.build({
    entryPoints,
    outdir: dist,
    bundle: true,
    // Shared runtime and a11y code lands in one chunk instead of being copied
    // into every component.
    splitting: true,
    chunkNames: "chunks/[name]-[hash]",
    format: "esm",
    target: "es2022",
    minify: true,
    sourcemap: true,
  });

  return Object.keys(entryPoints).length;
}

/**
 * Concatenate and minify. In the fetched stylesheet the `/*!` headers survive
 * so each block stays attributable; in the inlined critical CSS every byte is
 * paid on every page view, so comments are dropped entirely.
 */
async function minifyStyles(sources, { keepHeaders }) {
  const files = await existing(sources);
  if (files.length === 0) return null;

  const parts = [];
  for (const file of files) parts.push(await readFile(file, "utf8"));

  const { code } = await esbuild.transform(parts.join("\n"), {
    loader: "css",
    minify: true,
    legalComments: keepHeaders ? "inline" : "none",
  });
  return code.trim();
}

async function buildStylesheet(components) {
  const code = await minifyStyles(
    [
      path.join(src, "base", "motion.css"),
      path.join(src, "base", "scroll.css"),
      path.join(src, "base", "site.css"),
      ...components.map((name) =>
        path.join(src, "components", name, `${name}.css`),
      ),
    ],
    { keepHeaders: true },
  );
  if (code === null) return null;

  await writeFile(path.join(dist, "rc.css"), GENERATED_HEADER + code);
  return code.length;
}

/**
 * head.html = head.template.html with the critical CSS inlined and the CDN
 * location stamped into every URL. Every placeholder must be present in the
 * template; a silent no-op here would ship a broken head.
 */
async function buildHead() {
  const template = await readFile(
    path.join(embeds, "head.template.html"),
    "utf8",
  );
  const manifest = JSON.parse(
    await readFile(path.join(root, "package.json"), "utf8"),
  );
  const { ref, origin, base } = cdnLocation(manifest);
  // A component whose initial state must exist before first paint (anything
  // above the fold that starts hidden or pinned) ships it as
  // <name>.critical.css; it rides along inline instead of waiting for rc.css.
  const components = await findComponents();
  const critical =
    (await minifyStyles(
      [
        path.join(src, "base", "critical.css"),
        ...components.map((name) =>
          path.join(src, "components", name, `${name}.critical.css`),
        ),
      ],
      { keepHeaders: false },
    )) ?? "";

  const placeholders = [
    "{{cdn-ref}}",
    "{{cdn-origin}}",
    "{{cdn-base}}",
    "{{library-preconnect}}",
    "{{critical-css}}",
  ];
  for (const placeholder of placeholders) {
    if (!template.includes(placeholder)) {
      throw new Error(`head.template.html is missing ${placeholder}`);
    }
  }

  // GSAP and Lenis come from jsDelivr whatever mode dist/ is in; warm that
  // connection too unless it is already the dist origin.
  const libraryPreconnect =
    origin === LIBRARY_ORIGIN
      ? ""
      : `<link rel="preconnect" href="${LIBRARY_ORIGIN}" crossorigin />\n`;

  const html = template
    .replaceAll("{{cdn-ref}}", ref)
    .replaceAll("{{cdn-origin}}", origin)
    .replaceAll("{{cdn-base}}", base)
    .replace("{{library-preconnect}}", libraryPreconnect)
    .replace("{{critical-css}}", critical);

  await writeFile(path.join(embeds, "head.html"), html);
  return { ref, base, criticalBytes: critical.length };
}

/** Clear only what this script owns; anything else in dist/ survives. */
async function clearOwnOutput() {
  const owned = ["chunks", "components", "rc.js", "rc.js.map", "rc.css"];
  for (const entry of owned) {
    await rm(path.join(dist, entry), { recursive: true, force: true });
  }
  await mkdir(dist, { recursive: true });
}

function report(label, bytes) {
  return `${label.padEnd(18)}${bytes === null ? "no source yet" : `${bytes} B`}`;
}

async function main() {
  const components = await findComponents();

  await clearOwnOutput();

  const scriptCount = await buildScripts(components);
  const stylesheetBytes = await buildStylesheet(components);
  const head = await buildHead();

  console.log(
    [
      `cdn             ${head.base}  (@${head.ref})`,
      `components      ${components.length} (${components.join(", ") || "none"})`,
      `js entries      ${scriptCount}`,
      report("rc.css", stylesheetBytes),
      report("critical (inline)", head.criticalBytes),
      `head.html       webflow/embeds/head.html`,
    ].join("\n"),
  );
}

await main();
